
package Visualização;

import ModeloBeans.Exemplar;
import ModeloBeans.Pessoa;
import ModeloDAO.Exemplar_DAO;
import ModeloDAO.Pessoa_DAO;
import javax.swing.JOptionPane;

public class Cad_locatario extends javax.swing.JFrame {

    /**
     * Creates new form Cad_livro
     */
    
    Pessoa pessoa = new Pessoa();
    Pessoa_DAO pessoaDAO = new Pessoa_DAO();
    
    
    public Cad_locatario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Cadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5Telefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2CPF = new javax.swing.JTextField();
        jTextField7Endereco = new javax.swing.JTextField();
        jTextField8Sexo = new javax.swing.JTextField();
        jTextField3Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1Fundo2Cad_livro = new javax.swing.JLabel();
        jLabel1FundoCadLivr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1Cadastrar.setText("Cadastrar");
        jButton1Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Cadastrar);
        jButton1Cadastrar.setBounds(480, 280, 120, 50);

        jLabel4.setText("CPF");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 40, 90, 20);

        jLabel5.setText("Telefone");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 30, 150, 30);

        jTextField5Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5TelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5Telefone);
        jTextField5Telefone.setBounds(330, 70, 180, 29);

        jLabel7.setText("Sexo");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 110, 100, 20);

        jTextField2CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2CPFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2CPF);
        jTextField2CPF.setBounds(60, 70, 180, 29);

        jTextField7Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7EnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7Endereco);
        jTextField7Endereco.setBounds(60, 210, 180, 29);

        jTextField8Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8SexoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8Sexo);
        jTextField8Sexo.setBounds(330, 140, 180, 29);

        jTextField3Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3NomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3Nome);
        jTextField3Nome.setBounds(60, 140, 180, 29);

        jLabel2.setText("Endereco");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 180, 90, 20);

        jLabel3.setText("Nome");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 100, 20);

        jLabel1Fundo2Cad_livro.setBackground(new java.awt.Color(192, 200, 222));
        jLabel1Fundo2Cad_livro.setOpaque(true);
        getContentPane().add(jLabel1Fundo2Cad_livro);
        jLabel1Fundo2Cad_livro.setBounds(20, 20, 580, 320);

        jLabel1FundoCadLivr.setBackground(new java.awt.Color(89, 125, 192));
        jLabel1FundoCadLivr.setOpaque(true);
        getContentPane().add(jLabel1FundoCadLivr);
        jLabel1FundoCadLivr.setBounds(-40, -23, 710, 400);

        setSize(new java.awt.Dimension(634, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2CPFActionPerformed

    private void jTextField3NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3NomeActionPerformed

    private void jTextField5TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5TelefoneActionPerformed

    private void jTextField7EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7EnderecoActionPerformed

    private void jTextField8SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8SexoActionPerformed

    private void jButton1CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CadastrarActionPerformed
        try{
            Long cpf = Long.parseLong(jTextField2CPF.getText());
            pessoa.setCpf(cpf);
            pessoa.setEndereco(jTextField7Endereco.getText());
            pessoa.setNome(jTextField3Nome.getText());
            pessoa.setTelefone(jTextField5Telefone.getText());
            String Sexo;
            char sexo;
            sexo=jTextField8Sexo.getText().charAt(0);
            pessoa.setSexo(sexo);
            pessoaDAO.inserir(pessoa);
            dispose();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Dados incorretos"+e);
        }
        
        

    }//GEN-LAST:event_jButton1CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_locatario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Cadastrar;
    private javax.swing.JLabel jLabel1Fundo2Cad_livro;
    private javax.swing.JLabel jLabel1FundoCadLivr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2CPF;
    private javax.swing.JTextField jTextField3Nome;
    private javax.swing.JTextField jTextField5Telefone;
    private javax.swing.JTextField jTextField7Endereco;
    private javax.swing.JTextField jTextField8Sexo;
    // End of variables declaration//GEN-END:variables
}
