
package Visualização;

import ModeloBeans.Exemplar;
import ModeloDAO.Exemplar_DAO;
import javax.swing.JOptionPane;

public class Cad_livro extends javax.swing.JFrame {

    /**
     * Creates new form Cad_livro
     */
    
    Exemplar livro = new Exemplar();
    Exemplar_DAO livroDAO = new Exemplar_DAO();
    
    public Cad_livro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Cadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4Edi = new javax.swing.JTextField();
        jTextField5Edit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField6Quant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2ISBN = new javax.swing.JTextField();
        jTextField7Autor = new javax.swing.JTextField();
        jTextField8Vol = new javax.swing.JTextField();
        jTextField3Titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1Fundo2Cad_livro = new javax.swing.JLabel();
        jLabel1FundoCadLivr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1Cadastrar.setText("Cadastrar");
        jButton1Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Cadastrar);
        jButton1Cadastrar.setBounds(330, 260, 100, 40);

        jLabel4.setText("ISBN");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 40, 90, 20);

        jLabel5.setText("Editora");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 30, 150, 30);

        jTextField4Edi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4EdiActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4Edi);
        jTextField4Edi.setBounds(330, 210, 180, 29);

        jTextField5Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5EditActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5Edit);
        jTextField5Edit.setBounds(330, 70, 180, 29);

        jLabel1.setText("Quantidade");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 250, 100, 20);

        jTextField6Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6QuantActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6Quant);
        jTextField6Quant.setBounds(60, 280, 80, 29);

        jLabel6.setText("Edição");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 180, 70, 20);

        jLabel7.setText("Volume");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 110, 100, 20);

        jTextField2ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ISBNActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2ISBN);
        jTextField2ISBN.setBounds(60, 70, 180, 29);

        jTextField7Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7AutorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7Autor);
        jTextField7Autor.setBounds(60, 210, 180, 29);

        jTextField8Vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8VolActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8Vol);
        jTextField8Vol.setBounds(330, 140, 180, 29);

        jTextField3Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3TituloActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3Titulo);
        jTextField3Titulo.setBounds(60, 140, 180, 29);

        jLabel2.setText("Autor");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 180, 90, 20);

        jLabel3.setText("Titulo");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 100, 20);

        jLabel1Fundo2Cad_livro.setBackground(new java.awt.Color(192, 200, 222));
        jLabel1Fundo2Cad_livro.setOpaque(true);
        getContentPane().add(jLabel1Fundo2Cad_livro);
        jLabel1Fundo2Cad_livro.setBounds(20, 20, 580, 310);

        jLabel1FundoCadLivr.setBackground(new java.awt.Color(89, 125, 192));
        jLabel1FundoCadLivr.setOpaque(true);
        getContentPane().add(jLabel1FundoCadLivr);
        jLabel1FundoCadLivr.setBounds(-40, -23, 710, 380);

        setSize(new java.awt.Dimension(634, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ISBNActionPerformed

    private void jTextField3TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3TituloActionPerformed

    private void jTextField4EdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4EdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4EdiActionPerformed

    private void jTextField5EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5EditActionPerformed

    private void jTextField6QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6QuantActionPerformed

    private void jTextField7AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7AutorActionPerformed

    private void jTextField8VolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8VolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8VolActionPerformed

    private void jButton1CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CadastrarActionPerformed
        try{
            livro.setAutor(jTextField7Autor.getText());
            livro.setEdicao(jTextField4Edi.getText());
            Long isbn = Long.parseLong(jTextField2ISBN.getText());
            livro.setISBN(isbn);
            livro.setEditora(jTextField5Edit.getText());
            int quant = Integer.parseInt(jTextField6Quant.getText());
            livro.setQuantiade(quant);
            int vol = Integer.parseInt(jTextField8Vol.getText());
            livro.setVolume(vol);
            livro.setTitulo(jTextField3Titulo.getText());
            System.out.println(livro.getAutor());
            livroDAO.inserir(livro);
            dispose();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Dados incorretos\n"+e);
        }
        
    }//GEN-LAST:event_jButton1CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_livro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Fundo2Cad_livro;
    private javax.swing.JLabel jLabel1FundoCadLivr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2ISBN;
    private javax.swing.JTextField jTextField3Titulo;
    private javax.swing.JTextField jTextField4Edi;
    private javax.swing.JTextField jTextField5Edit;
    private javax.swing.JTextField jTextField6Quant;
    private javax.swing.JTextField jTextField7Autor;
    private javax.swing.JTextField jTextField8Vol;
    // End of variables declaration//GEN-END:variables
}
