
package Visualização;

import ModeloBeans.Exemplar;
import ModeloBeans.ModeloTabela;
import ModeloConnection.Banco;
import ModeloDAO.Exemplar_DAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Consult_livro extends javax.swing.JFrame {

    /**
     * Creates new form Cad_livro
     */
    
    Exemplar livro = new Exemplar();
    Exemplar_DAO livroDAO = new Exemplar_DAO();
    Banco bd = new Banco();
    
    public Consult_livro() {
        initComponents();
        preencherTabela("select * from exemplar order by titulo;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Pesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jTextField5Edit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField6Quant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1Excluir = new javax.swing.JButton();
        jButton1Editar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaLivros = new javax.swing.JTable();
        jTextField4Edi1 = new javax.swing.JTextField();
        jTextField2ISBN = new javax.swing.JTextField();
        jTextField7Autor = new javax.swing.JTextField();
        jTextField8Vol = new javax.swing.JTextField();
        jTextField3Titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1Fundo2Cad_livro = new javax.swing.JLabel();
        jLabel1FundoCadLivr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1Pesquisar.setText("Pesquisar");
        jButton1Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Pesquisar);
        jButton1Pesquisar.setBounds(230, 30, 110, 30);

        jLabel4.setText("ISBN");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 90, 20);

        jLabel5.setText("Editora");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 110, 150, 20);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(30, 30, 180, 29);

        jTextField5Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5EditActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5Edit);
        jTextField5Edit.setBounds(230, 140, 180, 29);

        jLabel1.setText("Quantidade");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 320, 100, 20);

        jTextField6Quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6QuantActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6Quant);
        jTextField6Quant.setBounds(30, 350, 80, 29);

        jLabel6.setText("Edição");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 250, 70, 20);

        jLabel7.setText("Volume");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 180, 100, 20);

        jButton1Excluir.setText("Excluir");
        jButton1Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Excluir);
        jButton1Excluir.setBounds(300, 350, 110, 30);

        jButton1Editar.setText("Editar");
        jButton1Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Editar);
        jButton1Editar.setBounds(180, 350, 100, 30);

        jTableTabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableTabelaLivros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 20, 600, 380);

        jTextField4Edi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4Edi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4Edi1);
        jTextField4Edi1.setBounds(230, 280, 180, 29);

        jTextField2ISBN.setEnabled(false);
        jTextField2ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ISBNActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2ISBN);
        jTextField2ISBN.setBounds(30, 140, 180, 29);

        jTextField7Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7AutorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7Autor);
        jTextField7Autor.setBounds(30, 280, 180, 29);

        jTextField8Vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8VolActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8Vol);
        jTextField8Vol.setBounds(230, 210, 180, 29);

        jTextField3Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3TituloActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3Titulo);
        jTextField3Titulo.setBounds(30, 210, 180, 30);

        jLabel2.setText("Autor");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 250, 90, 20);

        jLabel3.setText("Titulo");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 100, 20);

        jLabel1Fundo2Cad_livro.setBackground(new java.awt.Color(192, 200, 222));
        jLabel1Fundo2Cad_livro.setOpaque(true);
        getContentPane().add(jLabel1Fundo2Cad_livro);
        jLabel1Fundo2Cad_livro.setBounds(20, 20, 400, 380);

        jLabel1FundoCadLivr.setBackground(new java.awt.Color(89, 125, 192));
        jLabel1FundoCadLivr.setOpaque(true);
        getContentPane().add(jLabel1FundoCadLivr);
        jLabel1FundoCadLivr.setBounds(-90, -10, 1130, 450);

        setSize(new java.awt.Dimension(1053, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ISBNActionPerformed

    private void jTextField3TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3TituloActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jTextField5EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5EditActionPerformed

    private void jTextField6QuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6QuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6QuantActionPerformed

    private void jTextField7AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7AutorActionPerformed

    private void jTextField8VolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8VolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8VolActionPerformed

    private void jButton1PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PesquisarActionPerformed
                    
            livro.setPesquisa(jTextFieldPesquisa.getText());
            livro = livroDAO.buscaExemplar(livro);
            jTextField2ISBN.setText(String.valueOf(livro.getISBN()));
            jTextField2ISBN.enable(false);
            jTextField3Titulo.setText(livro.getTitulo());
            jTextField4Edi1.setText(livro.getEdicao());
            jTextField5Edit.setText(livro.getEditora());
            jTextField8Vol.setText(String.valueOf(livro.getVolume()));
            jTextField7Autor.setText(livro.getAutor());
            jTextField6Quant.setText(String.valueOf(livro.getQuantiade()));
        
        

    }//GEN-LAST:event_jButton1PesquisarActionPerformed

    private void jButton1EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EditarActionPerformed
        try{
            livro.setAutor(jTextField7Autor.getText());
            livro.setEdicao(jTextField4Edi1.getText());
            Long isbn = Long.parseLong(jTextField2ISBN.getText());
            int quant = Integer.parseInt(jTextField6Quant.getText());
            livro.setQuantiade(quant);
            int vol = Integer.parseInt(jTextField8Vol.getText());
            livro.setVolume(vol);
            livro.setTitulo(jTextField3Titulo.getText());
            livroDAO.editar(livro);
            preencherTabela("select * from exemplar order by titulo;");

            limpaCampos();
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Dados incorretos"+e);
        }
        
    }//GEN-LAST:event_jButton1EditarActionPerformed
    
    public void limpaCampos(){
        jTextField8Vol.setText("");
        jTextField2ISBN.setText("");
        jTextField3Titulo.setText("");
        jTextField7Autor.setText("");
        jTextField6Quant.setText("");
        jTextField5Edit.setText("");
        jTextField4Edi1.setText("");
    }
    
    private void jTextField4Edi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4Edi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4Edi1ActionPerformed

    private void jButton1ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExcluirActionPerformed
        livroDAO.deletar(Long.parseLong(jTextField2ISBN.getText()));
        preencherTabela("select * from exemplar order by titulo;");
        limpaCampos();
    }//GEN-LAST:event_jButton1ExcluirActionPerformed
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Titulo","Autor","Editora","Volume","Edicao","Quantidade","Isbn"};
        
        bd.conecta();
        
        bd.executaSQL(Sql);
        
        try{
            bd.rst.first();
            do{
 
                dados.add(new Object[]{bd.rst.getString("titulo"), bd.rst.getString("autor"), bd.rst.getString("editora"), bd.rst.getInt("volume"),bd.rst.getString("edicao"),bd.rst.getInt("quantidade"),bd.rst.getLong("isbn")});
                
            }while(bd.rst.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableTabelaLivros.setModel(modelo);
        
        /*
        jTableTabelaLivros.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableTabelaLivros.getColumnModel().getColumn(1).setPreferredWidth(25);
        jTableTabelaLivros.getColumnModel().getColumn(2).setPreferredWidth(25 );
        jTableTabelaLivros.getColumnModel().getColumn(3).setPreferredWidth(25);
        */
        
        bd.desconecta();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consult_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consult_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consult_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consult_livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consult_livro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Editar;
    private javax.swing.JButton jButton1Excluir;
    private javax.swing.JButton jButton1Pesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Fundo2Cad_livro;
    private javax.swing.JLabel jLabel1FundoCadLivr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaLivros;
    private javax.swing.JTextField jTextField2ISBN;
    private javax.swing.JTextField jTextField3Titulo;
    private javax.swing.JTextField jTextField4Edi1;
    private javax.swing.JTextField jTextField5Edit;
    private javax.swing.JTextField jTextField6Quant;
    private javax.swing.JTextField jTextField7Autor;
    private javax.swing.JTextField jTextField8Vol;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
