/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualização;

import ModeloBeans.ModeloTabela;
import ModeloBeans.Pessoa;
import ModeloConnection.Banco;
import ModeloDAO.Pessoa_DAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class Consult_locatario extends javax.swing.JFrame {

    /**
     * Creates new form Consult_locatario
     */
    
    Pessoa pessoa = new Pessoa();
    Pessoa_DAO pessoaDAO = new Pessoa_DAO();
    Banco bd = new Banco();

    
    public Consult_locatario() {
        initComponents();
        preencherTabela("select * from pessoa order by nome;");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButton1Pesquisar = new javax.swing.JButton();
        jTextFieldCPF = new javax.swing.JTextField();
        jButton1Editar = new javax.swing.JButton();
        jButton1Excluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSexo = new javax.swing.JTextField();
        jLabel1Fundo2Cad_livro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaLocatario = new javax.swing.JTable();
        jLabel1FundoCadLivr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(20, 290, 180, 22);

        jLabel2.setText("Endereco");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 260, 90, 20);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(20, 220, 180, 22);

        jLabel3.setText("Nome");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 100, 20);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(20, 50, 180, 22);

        jButton1Pesquisar.setText("Pesquisar");
        jButton1Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Pesquisar);
        jButton1Pesquisar.setBounds(230, 50, 110, 30);

        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF);
        jTextFieldCPF.setBounds(20, 150, 180, 22);

        jButton1Editar.setText("Editar");
        jButton1Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Editar);
        jButton1Editar.setBounds(180, 350, 100, 30);

        jButton1Excluir.setText("Excluir");
        jButton1Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Excluir);
        jButton1Excluir.setBounds(300, 350, 110, 30);

        jLabel4.setText("CPF");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 90, 20);

        jLabel5.setText("Telefone");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 190, 70, 20);

        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(220, 220, 180, 22);

        jLabel7.setText("Sexo");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 260, 100, 20);

        jTextFieldSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSexoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSexo);
        jTextFieldSexo.setBounds(220, 290, 180, 22);

        jLabel1Fundo2Cad_livro.setBackground(new java.awt.Color(192, 200, 222));
        jLabel1Fundo2Cad_livro.setOpaque(true);
        getContentPane().add(jLabel1Fundo2Cad_livro);
        jLabel1Fundo2Cad_livro.setBounds(10, 20, 450, 410);

        jTableTabelaLocatario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableTabelaLocatario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 20, 470, 410);

        jLabel1FundoCadLivr.setBackground(new java.awt.Color(89, 125, 192));
        jLabel1FundoCadLivr.setOpaque(true);
        getContentPane().add(jLabel1FundoCadLivr);
        jLabel1FundoCadLivr.setBounds(-90, -10, 1130, 480);

        setSize(new java.awt.Dimension(971, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    private void jTextFieldSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSexoActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButton1PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PesquisarActionPerformed
        pessoa.setPesquisa(jTextFieldPesquisa.getText());
        pessoa = pessoaDAO.BuscaPessoa(pessoa);
        jTextFieldCPF.setText(String.valueOf(pessoa.getCpf()));
        jTextFieldCPF.enable(false);
        jTextFieldEndereco.setText(pessoa.getEndereco());
        jTextFieldNome.setText(pessoa.getNome());
        jTextFieldTelefone.setText(pessoa.getTelefone());
        jTextFieldSexo.setText(String.valueOf(pessoa.getSexo()));
    }//GEN-LAST:event_jButton1PesquisarActionPerformed

    private void jButton1EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EditarActionPerformed
        pessoa.setEndereco(jTextFieldEndereco.getText());
        pessoa.setNome(jTextFieldNome.getText());
        Long cpf = Long.parseLong(jTextFieldCPF.getText());
        char sex = (jTextFieldSexo.getText()).charAt(0);
        pessoa.setCpf(cpf);
        pessoa.setSexo(sex);
        pessoa.setTelefone(jTextFieldTelefone.getText());
        pessoaDAO.editarPessoa(pessoa);
               
        preencherTabela("select * from pessoa order by nome;");

        limpaCampos();
    }//GEN-LAST:event_jButton1EditarActionPerformed

    private void jButton1ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExcluirActionPerformed
        pessoaDAO.deletar(Long.parseLong(jTextFieldCPF.getText()));
        preencherTabela("select * from pessoa order by nome;");
        limpaCampos();
    }//GEN-LAST:event_jButton1ExcluirActionPerformed
    
    public void limpaCampos(){
        jTextFieldCPF.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNome.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldSexo.setText("");
        jTextFieldTelefone.setText("");
    }
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Nome","CPF","Endereco","Sexo","Telefone"};
        
        bd.conecta();
        
        bd.executaSQL(Sql);
        
        try{
            bd.rst.first();
            do{
 
                dados.add(new Object[]{bd.rst.getString("nome"), bd.rst.getLong("cpf"), bd.rst.getString("endereco"), bd.rst.getString("sexo"),bd.rst.getString("telefone")});
                
            }while(bd.rst.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableTabelaLocatario.setModel(modelo);
        
        /*
        jTableTabelaLivros.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableTabelaLivros.getColumnModel().getColumn(1).setPreferredWidth(25);
        jTableTabelaLivros.getColumnModel().getColumn(2).setPreferredWidth(25 );
        jTableTabelaLivros.getColumnModel().getColumn(3).setPreferredWidth(25);
        */
        
        bd.desconecta();
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consult_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consult_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consult_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consult_locatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consult_locatario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Editar;
    private javax.swing.JButton jButton1Excluir;
    private javax.swing.JButton jButton1Pesquisar;
    private javax.swing.JLabel jLabel1Fundo2Cad_livro;
    private javax.swing.JLabel jLabel1FundoCadLivr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaLocatario;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
