/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualização;

import java.awt.Cursor;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextPane;
import javax.swing.WindowConstants;


public class HomePage extends javax.swing.JFrame {
    
    private String nome;
    public String mensagem=nome;
    public boolean adm;
    public long vol;
    
    
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    public String getNome() {
        return nome;
    }
    
    public HomePage() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensagem = new javax.swing.JLabel();
        jTabbedPane1FundoHome = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton2ConsultLivro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3cad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton8ConsultLocatario = new javax.swing.JButton();
        jLabel4CadLocatario = new javax.swing.JLabel();
        jLabel5CadLocatario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2ConsultEmp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton10ConsultVolum = new javax.swing.JButton();
        jButton1CadVolun = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabelMensagem.setBackground(new java.awt.Color(192, 200, 222));
        jLabelMensagem.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensagem.setText(nome);
        jLabelMensagem.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabelMensagem.setOpaque(true);
        getContentPane().add(jLabelMensagem);
        jLabelMensagem.setBounds(90, 10, 240, 40);

        jTabbedPane1FundoHome.setBackground(new java.awt.Color(165, 175, 228));
        jTabbedPane1FundoHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1FundoHome.setForeground(new java.awt.Color(5, 4, 1));
        jTabbedPane1FundoHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1FundoHome.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(192, 200, 222));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(null);

        jButton2ConsultLivro.setText("Consultar");
        jButton2ConsultLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ConsultLivroActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2ConsultLivro);
        jButton2ConsultLivro.setBounds(170, 60, 150, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 90, 80, 30);

        jLabel3cad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3cad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-cadastro-png-7(1).png"))); // NOI18N
        jLabel3cad.setToolTipText("");
        jLabel3cad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3cad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3cadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3cadMouseEntered(evt);
            }
        });
        jPanel2.add(jLabel3cad);
        jLabel3cad.setBounds(30, 30, 70, 70);

        jTabbedPane1FundoHome.addTab("Livros", jPanel2);

        jPanel1.setBackground(new java.awt.Color(192, 200, 222));
        jPanel1.setLayout(null);

        jButton8ConsultLocatario.setText("Consultar");
        jButton8ConsultLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ConsultLocatarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8ConsultLocatario);
        jButton8ConsultLocatario.setBounds(170, 60, 150, 40);

        jLabel4CadLocatario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4CadLocatario.setText("Cadastro");
        jLabel4CadLocatario.setToolTipText("");
        jLabel4CadLocatario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4CadLocatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4CadLocatarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4CadLocatarioMouseEntered(evt);
            }
        });
        jPanel1.add(jLabel4CadLocatario);
        jLabel4CadLocatario.setBounds(20, 90, 80, 20);

        jLabel5CadLocatario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5CadLocatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-cadastro-png-7(1).png"))); // NOI18N
        jLabel5CadLocatario.setToolTipText("");
        jLabel5CadLocatario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5CadLocatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5CadLocatarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5CadLocatarioMouseEntered(evt);
            }
        });
        jPanel1.add(jLabel5CadLocatario);
        jLabel5CadLocatario.setBounds(30, 50, 60, 40);

        jTabbedPane1FundoHome.addTab("Locatarios", jPanel1);

        jPanel3.setBackground(new java.awt.Color(192, 200, 222));
        jPanel3.setLayout(null);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(21, 61, 150, 40);

        jButton2ConsultEmp.setText("Consultar");
        jButton2ConsultEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ConsultEmpActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2ConsultEmp);
        jButton2ConsultEmp.setBounds(200, 60, 150, 40);

        jTabbedPane1FundoHome.addTab("Emprestimo", jPanel3);

        jPanel4.setBackground(new java.awt.Color(192, 200, 222));
        jPanel4.setToolTipText("");
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(null);

        jButton10ConsultVolum.setText("Consultar");
        jButton10ConsultVolum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ConsultVolumActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10ConsultVolum);
        jButton10ConsultVolum.setBounds(200, 60, 150, 40);

        jButton1CadVolun.setText("Cadastrar");
        jButton1CadVolun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CadVolunActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1CadVolun);
        jButton1CadVolun.setBounds(20, 60, 150, 40);

        jTabbedPane1FundoHome.addTab("Voluntários", jPanel4);

        getContentPane().add(jTabbedPane1FundoHome);
        jTabbedPane1FundoHome.setBounds(20, 70, 370, 220);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 60, 390, 10);

        jLabel1.setBackground(new java.awt.Color(98, 116, 184));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 330);

        setSize(new java.awt.Dimension(423, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ConsultLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ConsultLivroActionPerformed
        Consult_livro tela = new Consult_livro();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton2ConsultLivroActionPerformed

    private void jButton8ConsultLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ConsultLocatarioActionPerformed
        Consult_locatario tela = new Consult_locatario();
        tela.setVisible(true);
    }//GEN-LAST:event_jButton8ConsultLocatarioActionPerformed

    private void jButton10ConsultVolumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ConsultVolumActionPerformed
        if(adm){
            ConsultVoluntario tela = new ConsultVoluntario();
            tela.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Você não tem permissao para essa funcionalidade");
        }
        
    }//GEN-LAST:event_jButton10ConsultVolumActionPerformed

    private void jButton1CadVolunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CadVolunActionPerformed
        
        if(adm){
            Cad_volunt tela = new Cad_volunt();
            tela.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Você não tem permissao para essa funcionalidade");
        }
        
        
    }//GEN-LAST:event_jButton1CadVolunActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
    
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel3cadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3cadMouseClicked
        if(adm){            
            Cad_livro cadastroLivro = new Cad_livro();
            cadastroLivro.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Você não tem permissao para essa funcionalidade");
        }
        
    }//GEN-LAST:event_jLabel3cadMouseClicked

    private void jLabel3cadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3cadMouseEntered
        
    }//GEN-LAST:event_jLabel3cadMouseEntered

    private void jLabel4CadLocatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4CadLocatarioMouseClicked
       if(adm){            
            Cad_livro cadastroLivro = new Cad_livro();
            cadastroLivro.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Você não tem permissao para essa funcionalidade");
        }
        
    }//GEN-LAST:event_jLabel4CadLocatarioMouseClicked

    private void jLabel4CadLocatarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4CadLocatarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4CadLocatarioMouseEntered

    private void jLabel5CadLocatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5CadLocatarioMouseClicked
        // TODO add your handling code here:
        Cad_locatario cadastro = new Cad_locatario();
        cadastro.setVisible(true);
        
    }//GEN-LAST:event_jLabel5CadLocatarioMouseClicked

    private void jLabel5CadLocatarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5CadLocatarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5CadLocatarioMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cad_emprestimo tela = new cad_emprestimo();
        System.out.println("Voluntario"+vol);
        tela.volun=vol;
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ConsultEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ConsultEmpActionPerformed
       Consult_emprestimo tela = new Consult_emprestimo();
       tela.setVisible(true);
    }//GEN-LAST:event_jButton2ConsultEmpActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10ConsultVolum;
    private javax.swing.JButton jButton1CadVolun;
    private javax.swing.JButton jButton2ConsultEmp;
    private javax.swing.JButton jButton2ConsultLivro;
    private javax.swing.JButton jButton8ConsultLocatario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3cad;
    private javax.swing.JLabel jLabel4CadLocatario;
    private javax.swing.JLabel jLabel5CadLocatario;
    public javax.swing.JLabel jLabelMensagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1FundoHome;
    // End of variables declaration//GEN-END:variables
}
