/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualização;

import ModeloConnection.Banco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class TelaLogin extends javax.swing.JFrame {
     HomePage home = new HomePage();
     Banco bd = new Banco();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2Senha = new javax.swing.JLabel();
        jPasswordField1Senha = new javax.swing.JPasswordField();
        jButton1Sair = new javax.swing.JButton();
        jTextField1Login = new javax.swing.JTextField();
        jLabel1Usuario = new javax.swing.JLabel();
        jButton1Login = new javax.swing.JButton();
        jLabel1FundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel2Senha.setBackground(new java.awt.Color(254, 254, 254));
        jLabel2Senha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2Senha.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2Senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2Senha.setText("Senha");
        jLabel2Senha.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel2Senha.setOpaque(true);
        getContentPane().add(jLabel2Senha);
        jLabel2Senha.setBounds(100, 80, 60, 30);

        jPasswordField1Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1Senha);
        jPasswordField1Senha.setBounds(170, 80, 120, 29);

        jButton1Sair.setText("Sair");
        jButton1Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Sair);
        jButton1Sair.setBounds(220, 150, 90, 40);

        jTextField1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Login);
        jTextField1Login.setBounds(170, 40, 120, 30);

        jLabel1Usuario.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1Usuario.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel1Usuario.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Usuario.setText("Usuário");
        jLabel1Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1Usuario.setOpaque(true);
        getContentPane().add(jLabel1Usuario);
        jLabel1Usuario.setBounds(100, 40, 60, 30);

        jButton1Login.setText("Acessar");
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Login);
        jButton1Login.setBounds(100, 150, 100, 40);

        jLabel1FundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home-biblioteca2_0.jpg"))); // NOI18N
        getContentPane().add(jLabel1FundoLogin);
        jLabel1FundoLogin.setBounds(10, 0, 430, 257);

        setSize(new java.awt.Dimension(455, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1SairActionPerformed

    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed
        bd.conecta();
        try {
            bd.executaSQL("select * from voluntario where nome_usuario='"+jTextField1Login.getText()+"';");
            bd.rst.first();
            System.out.println(bd.rst.getString("senha"));
            if(bd.rst.getString("senha").equals(jPasswordField1Senha.getText())){                
                home.setNome(jTextField1Login.getText());
                home.jLabelMensagem.setText("Seja Bem vindo(a) "+jTextField1Login.getText());
                if(bd.rst.getBoolean("adm")){
                    home.adm=true;
                }else{
                    home.adm=false;
                }
                home.vol=bd.rst.getLong("cpf_voluntario");
                
                home.setVisible(true);
                bd.desconecta();
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Senha ou usuario Invalidos");
            }
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Senha ou usuario Invalidos "+ex);
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_jButton1LoginActionPerformed

    private void jTextField1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1LoginActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jTextField1LoginActionPerformed

    private void jPasswordField1SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1SenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Login;
    private javax.swing.JButton jButton1Sair;
    private javax.swing.JLabel jLabel1FundoLogin;
    private javax.swing.JLabel jLabel1Usuario;
    private javax.swing.JLabel jLabel2Senha;
    private javax.swing.JPasswordField jPasswordField1Senha;
    private javax.swing.JTextField jTextField1Login;
    // End of variables declaration//GEN-END:variables
}
